apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: iot-p2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: lrakai/tetris:latest
          ports:
            - containerPort: 80
