apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-funny-gitlab
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: __REPO_URL__
    targetRevision: main
    path: __REPO_PATH__
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
